#!/bin/bash

options="LogOut\nReboot\nPoweroff\nSuspend\nLock"

selected=$(echo -e "$options" | wofi --dmenu --prompt="Action:")

case $selected in
    "LogOut")
        swaymsg exit
        ;;
    "Reboot")
        systemctl reboot
        ;;
    "Poweroff")
        systemctl poweroff
        ;;
    "Suspend")
        systemctl suspend && swaylock
        ;;
    "Lock")
        swaylock
        ;;
    *)
        exit 1
        ;;
esac
